package POJOS;
// Generated Aug 4, 2020 3:13:08 PM by Hibernate Tools 4.3.1



/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private double balance;
     private String name;

    public Accounts() {
    }

    public Accounts(int id, String username, String password, double balance, String name) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.balance = balance;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


